
version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: deps
      prefix-development: deps(dev)
    

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "workflows"
