[package]
name = "perf-event-async"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-core = "0.3.25"
libc = "0.2.137"
perf-event = { git = "https://github.com/phantomical/perf-event", branch = "sampling-work" }
tokio = { version = "1.22.0", features = ["net"] }

[dev-dependencies]
assert_matches = "1.5.0"
nix = "0.25.0"
tokio = { version = "1.22.0", features = ["full", "test-util"] }
